// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_Api_Prueba.Data;

#nullable disable

namespace Web_Api_Prueba.Migrations
{
    [DbContext(typeof(ConexionContext))]
    partial class ConexionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_Api_Prueba.Models.CategoriaGasto", b =>
                {
                    b.Property<int>("IdCategoriaGasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoriaGasto"));

                    b.Property<int>("ContadorGastos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCategoriaGasto");

                    b.ToTable("CategoriaGastos", (string)null);
                });

            modelBuilder.Entity("Web_Api_Prueba.Models.Gasto", b =>
                {
                    b.Property<int>("IdGasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGasto"));

                    b.Property<int?>("CategoriaIdCategoriaGasto")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCategoriaGasto")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Monto")
                        .HasColumnType("real");

                    b.Property<int?>("UsuarioIdPersona")
                        .HasColumnType("int");

                    b.HasKey("IdGasto");

                    b.HasIndex("CategoriaIdCategoriaGasto");

                    b.HasIndex("UsuarioIdPersona");

                    b.ToTable("Gastos", (string)null);
                });

            modelBuilder.Entity("Web_Api_Prueba.Models.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersona"));

                    b.Property<bool>("Autenticado")
                        .HasColumnType("bit");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPersona");

                    b.ToTable("Personas", (string)null);
                });

            modelBuilder.Entity("Web_Api_Prueba.Models.Gasto", b =>
                {
                    b.HasOne("Web_Api_Prueba.Models.CategoriaGasto", "Categoria")
                        .WithMany("Gastos")
                        .HasForeignKey("CategoriaIdCategoriaGasto");

                    b.HasOne("Web_Api_Prueba.Models.Persona", "Usuario")
                        .WithMany("Gastos")
                        .HasForeignKey("UsuarioIdPersona");

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Web_Api_Prueba.Models.CategoriaGasto", b =>
                {
                    b.Navigation("Gastos");
                });

            modelBuilder.Entity("Web_Api_Prueba.Models.Persona", b =>
                {
                    b.Navigation("Gastos");
                });
#pragma warning restore 612, 618
        }
    }
}
